In [3]:
import numpy as np

vector1 = np.array([1,1])
rotation = np.array([np.cos(np.pi*(0.5)), np.sin(np.pi*(0.5))])
vector2 = rotation * vector1


[1 1] [6.123234e-17 1.000000e+00]


# 3.3a Complex number multiplication and rotation matrix

Euler equation $e^{i\theta}=cos(\theta)+isin(\theta)$

For a 2D vector being left mulitiplied by a complex number, it is equivalent to rotate the vector by the angle of the complex number.

$\begin{bmatrix}
cos(\theta) & -sin(\theta) \\ 
sin(\theta) & cos(\theta)
\end{bmatrix}\cdot 
\begin{bmatrix} 
a \\
b
\end{bmatrix}=e^{i\theta}\cdot
\begin{bmatrix} 
a \\
b
\end{bmatrix}$

# 3.3b 

$z = 0.5a_{F} + 0.5a_{G} + i(0.5b_{F}+0.5b_{G})$

No constraint on amplitude, it is not a rotation operation.

# 3.3c 

$z(t) = e^{i\theta_{F}(1-t)+i\theta_{G}t}$ works cuz it is a rotation operation, satisfies the unit length constraint

# 3.4


In [26]:
from pydrake.all import (
    PiecewiseQuaternionSlerp,
    RandomGenerator,
    UniformlyRandomQuaternion,
)

g = RandomGenerator()
q1 = UniformlyRandomQuaternion(g)
q2 = UniformlyRandomQuaternion(g)

alpha = 0.1
s1 = PiecewiseQuaternionSlerp([0, 1], [q1, q2])
s2 = PiecewiseQuaternionSlerp([0, 1 / alpha], [q1, q2])
print(s1.value(0.0))
print(s2.EvalDerivative(0.5 / alpha) / alpha)

[[-0.80029006]
 [ 0.47334852]
 [-0.07154014]
 [ 0.36105265]]
[[-0.81015336]
 [ 0.44432789]
 [-0.02966567]
 [ 0.38124035]]
[[-0.81750478]
 [ 0.41392963]
 [ 0.01230077]
 [ 0.40024603]]
[[-0.82232154]
 [ 0.38224797]
 [ 0.05422907]
 [ 0.41801074]]
[[-0.82458869]
 [ 0.34938116]
 [ 0.09598924]
 [ 0.43447942]]
[[-0.82429921]
 [ 0.3154311 ]
 [ 0.13745179]
 [ 0.44960099]]
[[ 0.11336442]
 [-0.54279188]
 [ 0.05152888]]
